dist: xenial
language: python
cache: pip
sudo: false
python:
    - "3.5"
    - "3.6"
install:
    - pip install -q -e .
    - pip install coverage coveralls
    - python setup.py develop

script:
    - coverage run --branch --source=. wirecloud/keycloak/tests/tests.py

after_success:
    - coveralls

branches:
    only:
        - master
