dist: xenial
language: python
cache: pip
sudo: false
python:
    - "3.5"
    - "3.6"
install:
    - pip install coverage
    - pip install coveralls
    - pip install "social-auth-app-django"
    - python setup.py develop

script:
    - coverage run --source=. wirecloud/keycloak/tests/tests.py

after_success:
    - coveralls

branches:
    only:
        - master